---
name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew check jacoco assemble

      - name: Codecov
        uses: codecov/codecov-action@v3
